name: LCTT Article Status

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TRAVIS_REPO_SLUG: ${{ github.repository }}
      TRAVIS_BRANCH: master
      TRAVIS_PULL_REQUEST: ${{ github.event.number }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Set ENV variables
        run: |
          echo "::set-env name=TRAVIS_BRANCH::${TRAVIS_BRANCH:-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')}" 
          echo "::set-env name=TRAVIS_EVENT_TYPE::$(if [ "schedule" == "${{ github.event_name }}" ]; then echo "cron"; else echo "${{ github.event_name }}"; fi)"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: checkout old pages branch
        uses: actions/checkout@v2
        with:
          repository: lctt/translateproject
          path: build
          ref: gh-pages
      - name: remove pages .git
        run: rm ./build/.git
      - name: run status
        run: sh ./scripts/status.sh;
      - uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          build_dir: ./build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
