name: LCTT Article Badge

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ${TRAVIS_BRANCH:-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')}
      - name: Set ENV variables
        run: |
          echo "::set-env name=TRAVIS_BRANCH::${TRAVIS_BRANCH:-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')}"
      - name: checkout old pages branch
        uses: actions/checkout@v2
        with:
          repository: lctt/translateproject
          path: build
          ref: gh-pages
      - name: remove pages .git
        run: rm -rf ./build/.git
      - name: run badge
        run: sh ./scripts/badge.sh;
      - uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          build_dir: ./build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
